version: "3.9"

services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: ragdb
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ragmq
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

  # server:
  #   image: learnify-backend:prod
  #   container_name: learnify-rag-server
  #   extra_hosts:
  #   - "host.docker.internal:host-gateway"
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - rabbitmq

  transcript-server:
    image: transcription-service:latest
    container_name: learnify-transcript-server
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq