spring.application.name=server

#db config
spring.datasource.url=jdbc:postgresql://localhost:5433/ragdb
spring.datasource.username=raguser
spring.datasource.password=ragpass

spring.ai.ollama.base-url=http://localhost:11434

# Chat model (Mistral) ( for question answering and the quiz generations)
spring.ai.ollama.chat.enabled=true
spring.ai.ollama.chat.model=mistral
spring.ai.ollama.chat.options.temperature=0.2

# Enable embedding model
spring.ai.ollama.embedding.enabled=true
# Embedding model name
spring.ai.ollama.embedding.model=nomic-embed-text

#PgVector config
#spring.ai.vectorstore.pgvector.index-type=HNSW
#spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
#spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.initialize-schema=true

