spring.application.name=server

#db config
spring.datasource.url=jdbc:postgresql://localhost:5433/ragdb
spring.datasource.username=raguser
spring.datasource.password=${DB_PASSWORD}

#used the groq for queries
spring.ai.openai.api-key=${GROQ_API}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.enabled=true
spring.ai.openai.embedding.enabled=false

#free tier model can use other later
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
spring.ai.openai.chat.options.temperature=0.7




#used the ollama for embeddings generations
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.enabled=false
spring.ai.ollama.embedding.enabled=true
spring.ai.ollama.embedding.model=nomic-embed-text

#PgVector config
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.initialize-schema=true

