spring.application.name=server



#used the groq for queries
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.enabled=true
spring.ai.openai.embedding.enabled=false

#free tier model can use other later
spring.ai.openai.chat.options.model=${GROQ_CHAT_MODEL}
spring.ai.openai.chat.options.temperature=0.7

# Configure spring limits
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


spring.profiles.active=${SPRING_PROFILES_ACTIVE}