# prod rabbitmq config
spring.rabbitmq.host=ragmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

transcription-service.base-url=${TRANSCRIPTION_WORKER_URL}

#multipart file  limit
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB